name: Main
on:
  - pull_request
jobs:
  Test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go get -u github.com/rakyll/gotest && export PATH=$PATH:$(go env GOPATH)/bin && make test-coverage

  Lint:
    name: Lint job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
